import Navbar from "../components/Navbar"
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Manager',
  description: 'Generated by create next app',
}
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body className={inter.className}>
            <Navbar/>
            <div className="p-4">
                {children}
            </div>
        </body>
      </html>
    )
  }
  