import './globals.css'
import { Inter } from 'next/font/google'
import { Toasterprovider } from './providers/Toasterprovider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toasterprovider/>
        {children}
        </body>
    </html>
  )
}
